services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

  flask_app:
    image: python:3.11-slim
    container_name: flask_app
    restart: always
    working_dir: /app
    volumes:
      - ./flask_app:/app
    command: >
      sh -c "apt-get update && apt-get install -y build-essential default-libmysqlclient-dev libssl-dev python3-dev pkg-config
      && pip install --upgrade pip
      && pip install -r requirements.txt
      && python3 app.py --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  node_app:
    image: node:20-alpine
    container_name: node_app
    restart: always
    working_dir: /app
    volumes:
      - ./node_app:/app
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  nextjs_app:
    image: node:20-alpine
    container_name: nextjs_app
    restart: always
    working_dir: /app
    volumes:
      - ./nextjs_app:/app
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo_express:
    image: mongo-express:1.0
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo